More console functionality. New provenance algorithm is now use. Changed some rest endpoints in order to have the administrative endpoints under /rest/admin.

diff --git a/git/config/git-hook_update b/git/config/git-hook_update
--- a/git/config/git-hook_update
+++ b/git/config/git-hook_update
@@ -5,10 +5,15 @@ df="[%Y-%m-%d %H:%M:%S]"
 echo "$(date +"$df") UPDATE HOOK called for ref $3"
 echo -e "Verifying upload, using rest service at: ${REST_SERVER}"
 
-upload_verification=$(curl -s -H "Accept: application/json" "${REST_SERVER}/rdf_verification/$3")
+upload_verification=$(curl -s -H "Accept: application/json" "${REST_SERVER}/query/commits/rdf_verification/$3")
 
 if [[ "$upload_verification" == *"403 Forbidden"* ]]; then
   echo "Access to REST Server forbidden!"
+  exit 1
+fi
+
+if [[ "$upload_verification" == *"404 Not Found"* ]]; then
+  echo "REST Verification endpoint not found!"
   exit 1
 fi
 
